"""initial schema

Revision ID: 4b551282b547
Revises: 
Create Date: 2026-09-11 11:53:31.060181
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '4b551282b547'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('isbn13', sa.String(length=13), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('has_fulltext', sa.Boolean(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_books_source'))
    )
    op.create_index(op.f('ix_books_isbn13'), 'books', ['isbn13'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('daily', 'weekly', 'once', name='challengeperiod', native_enum=False, length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges')),
    sa.UniqueConstraint('code', name=op.f('uq_challenges_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('book_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_chunks_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_chunks')),
    sa.UniqueConstraint('book_id', 'chunk_index', name=op.f('uq_book_chunks_book_id'))
    )
    op.create_table('library_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('shelf', sa.Enum('want', 'reading', 'done', name='shelf', native_enum=False, length=20), nullable=False),
    sa.Column('progress_pct', sa.SmallInteger(), nullable=False),
    sa.Column('verified_chunk', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('progress_pct BETWEEN 0 AND 100', name=op.f('ck_library_entries_progress_range')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_library_entries_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_library_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_entries')),
    sa.UniqueConstraint('user_id', 'book_id', name=op.f('uq_library_entries_user_id'))
    )
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_accounts')),
    sa.UniqueConstraint('provider', 'provider_user_id', name=op.f('uq_oauth_accounts_provider'))
    )
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_table('points_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_points_log_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_points_log'))
    )
    op.create_index(op.f('ix_points_log_user_id'), 'points_log', ['user_id'], unique=False)
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('anchor', sa.SmallInteger(), nullable=False),
    sa.Column('kind', sa.Enum('emoji', 'comment', name='reactionkind', native_enum=False, length=20), nullable=False),
    sa.Column('body', sa.String(length=280), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_reactions_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reactions'))
    )
    op.create_index('ix_reactions_book_chunk', 'reactions', ['book_id', 'chunk_index'], unique=False)
    op.create_table('reading_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('dwell_ms', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_reading_events_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reading_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_events'))
    )
    op.create_index('ix_reading_events_user_book', 'reading_events', ['user_id', 'book_id', 'chunk_index'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('mode', sa.Enum('sync', 'async', name='roommode', native_enum=False, length=20), nullable=False),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_rooms_book_id_books')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_rooms_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('invite_code', name=op.f('uq_rooms_invite_code'))
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_teams_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('page_race', 'highlight_battle', name='battletype', native_enum=False, length=20), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'active', 'finished', name='battlestatus', native_enum=False, length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('team_a_id <> team_b_id', name=op.f('ck_battles_distinct_teams')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_battles_book_id_books')),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], name=op.f('fk_battles_team_a_id_teams')),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], name=op.f('fk_battles_team_b_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_battles'))
    )
    op.create_table('room_members',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_members_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_room_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id', name=op.f('pk_room_members'))
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id', name=op.f('pk_team_members'))
    )
    op.create_table('highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('anchor', sa.SmallInteger(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('comment', sa.String(length=280), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], name=op.f('fk_highlights_battle_id_battles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_highlights_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_highlights_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_highlights'))
    )
    op.create_table('highlight_votes',
    sa.Column('highlight_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlights.id'], name=op.f('fk_highlight_votes_highlight_id_highlights'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_highlight_votes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('highlight_id', 'user_id', name=op.f('pk_highlight_votes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highlight_votes')
    op.drop_table('highlights')
    op.drop_table('team_members')
    op.drop_table('room_members')
    op.drop_table('battles')
    op.drop_table('teams')
    op.drop_table('rooms')
    op.drop_index('ix_reading_events_user_book', table_name='reading_events')
    op.drop_table('reading_events')
    op.drop_index('ix_reactions_book_chunk', table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_points_log_user_id'), table_name='points_log')
    op.drop_table('points_log')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_table('library_entries')
    op.drop_table('book_chunks')
    op.drop_table('users')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_books_isbn13'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
